default: &default
  adapter: mysql2
  host: host.docker.internal
  #host: 127.0.0.1
  #host: localhost
  username: root
  password: Pritika@29
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_development

production:
  <<: *default
  database: demo_production

test:
  <<: *default
  database: demo_test
